module.exports = {
  apps: [
    {
      name: 'kit-gateway',
      script: 'node',
      args: '--import tsx src/index.ts',
      cwd: 'c:\\dev\\kit\\gateway',
      watch: false,
      autorestart: true,
      max_restarts: 5,
      restart_delay: 3000,
      out_file: 'c:\\dev\\kit\\logs\\pm2-gateway.log',
      error_file: 'c:\\dev\\kit\\logs\\pm2-gateway.error.log',
      merge_logs: true,
    },
    {
      name: 'kit-daemon',
      script: 'node',
      args: '--import tsx src/index.ts',
      cwd: 'c:\\dev\\claude_whatsapp_integration',
      watch: false,
      autorestart: true,
      max_restarts: 5,
      restart_delay: 3000,
      out_file: 'c:\\dev\\kit\\logs\\pm2-daemon.log',
      error_file: 'c:\\dev\\kit\\logs\\pm2-daemon.error.log',
      merge_logs: true,
    },
    {
      name: 'kit-linkedin',
      script: 'node',
      args: '--import tsx src/index.ts',
      cwd: 'c:\\dev\\kit\\daemons\\linkedin',
      watch: false,
      autorestart: true,
      max_restarts: 3,
      restart_delay: 10000,
      out_file: 'c:\\dev\\kit\\logs\\pm2-linkedin.log',
      error_file: 'c:\\dev\\kit\\logs\\pm2-linkedin.error.log',
      merge_logs: true,
    },
    {
      name: 'kit-instagram',
      script: 'node',
      args: '--import tsx src/index.ts',
      cwd: 'c:\\dev\\kit\\daemons\\instagram',
      watch: false,
      autorestart: true,
      max_restarts: 3,
      restart_delay: 10000,
      out_file: 'c:\\dev\\kit\\logs\\pm2-instagram.log',
      error_file: 'c:\\dev\\kit\\logs\\pm2-instagram.error.log',
      merge_logs: true,
    },
  ],
};
